'use strict';
const arrow='<span aria-hidden="true">↗</span>';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intro=(label,title,body)=>`<div class="page-intro"><p class="eyebrow">${label}</p><h1>${title}</h1><p>${body}</p></div>`;
const cta=()=>`<section class="cta"><div><h2>Let’s begin with you.</h2><p>A personal consultation. Time to talk. Space to decide.</p></div><button class="btn" data-book aria-haspopup="dialog">Book Now ${arrow}</button></section>`;
const identity=()=>`<div class="doctor-identity"><span class="monogram" aria-hidden="true">E.</span><div class="doctor-name">Dr Elmira Yaghmaei</div><p>MD · GMC-registered doctor</p></div>`;
const qualifications=()=>`<ul class="qualifications"><li>MD · Medical degree</li><li>Level 7 Diploma in Cosmetic Injectables<small>Harley Academy</small></li><li>Cosmetic Dermatology course<small>Harley Academy</small></li><li>Aesthetics qualification<small>British Aesthetic Academy</small></li></ul>`;
const services=[
 {id:'facial-consultations',name:'Facial Aesthetic Consultations',lead:'A personal assessment of your facial concerns, with time to discuss suitability and your options.',items:['Facial lines and wrinkles consultation','Neck band consultation','Brow lift consultation','Lip flip consultation','Jawline slimming consultation']},
 {id:'dermal-fillers',name:'Dermal Fillers',lead:'Explore individual areas of the face with Dr Elmira, who will assess suitability and explain options and limitations.',items:['Lip filler','Tear trough filler','Jawline filler','Chin filler','Nasolabial fold filler','Marionette line filler','Cheek filler']},
 {id:'injectable-skin',name:'Injectable Skin Treatments',lead:'An individual consultation to discuss your skin, treatment options and what may be appropriate for you.',items:['Skin boosters','Profhilo','Polynucleotides']},
 {id:'skin-rejuvenation',name:'Skin Rejuvenation',lead:'Consider your skin concerns, preparation and aftercare with advice from Dr Elmira.',items:['Microneedling','Chemical peels']},
 {id:'other-consultations',name:'Other Consultations',lead:'A discreet conversation about your concerns and appropriate next steps, including further assessment or referral where needed.',items:['Teeth grinding and jaw clenching','Excessive underarm sweating']}
];
const slug=text=>text.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const treatmentHref=(service,item)=>`#${service.id}/${slug(item)}`;
const cards=()=>`<div class="category-grid">${services.map(s=>`<article class="category-card"><h3><a href="#${s.id}">${s.name} ${arrow}</a></h3><p>${s.lead}</p><ul>${s.items.map(item=>`<li><a href="${treatmentHref(s,item)}">${item} ${arrow}</a></li>`).join('')}</ul></article>`).join('')}</div>`;
const tabs=active=>`<nav class="category-nav" aria-label="Treatment categories">${services.map(s=>`<a href="#${s.id}" ${s.id===active?'aria-current="page"':''}>${s.name}</a>`).join('')}</nav>`;
function category(s){return intro('Treatments',s.name,s.lead)+`<section class="section category-page">${tabs(s.id)}<div class="category-body"><aside class="consultation-aside"><p class="eyebrow">Personally provided</p><h2>Your time.<br>Your doctor.</h2><p>Every consultation and treatment is with Dr Elmira.</p><p>Suitability, potential benefits, limitations, risks, alternatives and aftercare are discussed before any decision.</p><a class="text-link" href="#fees">View fees ${arrow}</a></aside><div class="treatment-list">${s.items.map(item=>`<details id="${slug(item)}"><summary>${item}</summary><p>${s.id==='other-consultations'?'Discuss your symptoms and their impact with Dr Elmira. Your consultation considers appropriate assessment and next steps, which may include referral.':'Discuss your concerns and goals with Dr Elmira. Your consultation includes an individual assessment and a discussion of suitable options, their limitations and potential risks.'} A consultation may or may not lead to treatment.</p><button class="btn" data-book aria-haspopup="dialog">Book Now ${arrow}</button></details>`).join('')}</div></div></section>`+cta()}
const feeGroup=(title,items)=>`<section class="fee-group"><h2>${title}</h2>${items.map(item=>`<div class="fee-row"><span>${item}</span><span>To be confirmed</span></div>`).join('')}</section>`;
const testimonials=()=>`<section class="section testimonials-section" aria-labelledby="reviews-heading"><div class="section-heading"><div><p class="eyebrow">Testimonials</p><h2 id="reviews-heading">Your experience matters.</h2></div></div><p class="review-disclosure">Design preview: spaces reserved for genuine patient reviews, shared with permission. No patient reviews have been added yet.</p><div class="review-grid">${['The consultation experience','Your treatment journey','Care and communication'].map(label=>`<article class="review-placeholder"><span class="review-mark" aria-hidden="true">“</span><p class="eyebrow">Patient review placeholder</p><h3>${label}</h3><p>A patient’s own words will appear here once a review is available and approved for publication.</p></article>`).join('')}</div></section>`;
function account(mode){const create=mode==='create-account';return intro('Your ELLE account',create?'Create an Account':'Sign In','A personal space for your clinic journey.')+`<section class="section account-layout"><div><p class="eyebrow">Care, connected</p><h2>Everything begins<br>with you.</h2><p>Account access will be available once the clinic’s secure patient service is connected.</p><a class="text-link" href="#contact">Contact Us ${arrow}</a></div><div class="account-panel"><div class="account-tabs"><a href="#create-account" ${create?'aria-current="page"':''}>Create an Account</a><a href="#signin" ${!create?'aria-current="page"':''}>Sign In</a></div><p class="status-note" id="account-notice">Design preview only. These fields are inactive; no details are collected and no account can be created.</p><form aria-describedby="account-notice"><fieldset disabled><legend>${create?'Account details':'Sign-in details'}</legend>${create?'<label>Full name<input type="text" autocomplete="off"></label>':''}<label>Email address<input type="email" autocomplete="off"></label><label>Password<input type="password" autocomplete="off"></label>${create?'<label class="account-consent"><input type="checkbox"> I agree to the Terms &amp; Conditions and have read the Privacy Policy.</label>':''}<button class="btn" type="button">${create?'Create an Account':'Sign In'}</button></fieldset></form><p class="account-policy"><a href="#terms">Terms &amp; Conditions</a> · <a href="#privacy">Privacy Policy</a></p></div></section>`}

/* Retained home and doctor content is inserted during the build. */
const pages={
home:()=>`<section class="hero"><div class="hero-copy"><p class="eyebrow">Doctor-led aesthetics · London</p><h1>Thoughtfully<br>considered.<em>Personally you.</em></h1><div class="accent-line" aria-hidden="true"></div><p>Individual care for your face, skin and body. Every consultation and treatment personally provided by Dr Elmira.</p><div class="hero-actions"><button class="btn" data-book aria-haspopup="dialog">Book Now ${arrow}</button><a class="text-link" href="#treatments">Explore Treatments ${arrow}</a></div><div class="hero-note">GMC-REGISTERED DOCTOR · MD</div></div><div class="hero-media"><img src="assets/hero.jpg" alt="Illustrative editorial portrait of a woman with natural skin texture" fetchpriority="high"><span class="image-note">ILLUSTRATIVE IMAGERY</span></div></section><div class="trust"><span>Every consultation with Dr Elmira</span><span>Every treatment performed by a doctor</span><span>Individual care for women & men</span></div><section class="section"><div class="section-heading"><div><p class="eyebrow">A personal approach to aesthetics</p><h2>Explore your possibilities.</h2></div><a class="text-link" href="#treatments">Discover our treatments ${arrow}</a></div>${cards()}</section><section class="section doctor-section">${identity()}<div><p class="eyebrow">Meet your doctor</p><h2>One doctor.<br>Your care, personally.</h2><p class="bodycopy">Elle Clinic is founded and run by Dr Elmira Yaghmaei. From your first conversation to your treatment, you’ll see the same doctor — someone who takes the time to understand you.</p><p class="bodycopy">Medical knowledge, aesthetic training and a thoughtful, individual approach.</p><a class="text-link" href="#doctor">Meet Dr Elmira ${arrow}</a></div></section><section class="section approach"><div><p class="eyebrow">The Elle approach</p><h2>Time to listen.<br>Carefully considered care.</h2></div><p>Your consultation is a space to ask questions, explore your options and understand what treatment can — and cannot — offer. Any recommendation begins with your individual needs and suitability. The decision is always yours.</p></section>${testimonials()}${cta()}`,
doctor:()=>intro('Meet Dr Elmira','Your doctor.<br>At every step.','A personal clinic, built around continuity of care. Every consultation and every treatment at Elle Clinic is provided by Dr Elmira Yaghmaei.')+`<section class="section doctor-section">${identity()}<div><p class="eyebrow">Dr Elmira Yaghmaei · MD</p><h2>Medicine meets<br>a considered approach.</h2><p class="bodycopy">I founded Elle Clinic to offer a personal approach to aesthetic care. I take the time to listen to your concerns, explain the available options and help you make an informed decision.</p><p class="bodycopy">You will meet with me for your consultation, and I will personally carry out any agreed treatment.</p>${qualifications()}</div></section><section class="section approach"><div><p class="eyebrow">Your consultation</p><h2>A conversation<br>before a decision.</h2></div><p>We’ll discuss your medical history, your concerns and your expectations. You’ll have the opportunity to ask about suitability, potential benefits, risks, alternatives and aftercare. A consultation may also conclude that treatment is not appropriate.</p></section>${cta()}`,
};
pages.treatments=()=>intro('Your care at ELLE Clinic','Treatments &amp; consultations.','Explore our five categories. Dr Elmira personally provides every consultation and treatment.')+`<section class="section category-page">${cards()}<p class="consultation-note">Treatment is subject to individual assessment, suitability and informed consent.</p></section>`+cta();
services.forEach(s=>pages[s.id]=()=>category(s));
pages.fees=()=>intro('Fees','Clear information.<br>Considered decisions.','Your proposed plan and its costs will be discussed before you decide to proceed.')+`<div class="fees-wrap"><p class="status-note">Prices are being finalised. No prices or consultation charges are confirmed in this preview.</p>${services.map(s=>feeGroup(s.name,s.items)).join('')}</div>`+cta();
pages.contact=()=>intro('Contact Us','A personal welcome.','Every consultation and treatment at ELLE Clinic is personally provided by Dr Elmira.')+`<section class="section contact-details"><div class="contact-detail-grid"><section class="contact-detail"><h2>Address</h2><p>London, United Kingdom</p><div class="blank-detail" aria-label="Full street address not yet provided"></div></section><section class="contact-detail"><h2>Contact number</h2><div class="blank-detail" aria-label="Contact number not yet provided"></div></section><section class="contact-detail"><h2>Email address</h2><div class="blank-detail" aria-label="Email address not yet provided"></div></section><section class="contact-detail"><h2>Opening hours</h2><dl class="hours"><div><dt>Monday to Friday</dt><dd>9 am – 7 pm</dd></div><div><dt>Saturday and Sunday</dt><dd>Closed</dd></div></dl></section></div><section class="map-placeholder"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><h2>Google Maps location</h2><p>Location link to be added.</p><span>London, United Kingdom</span></section></section>`+cta();
pages.testimonials=()=>intro('Patient experiences','Testimonials.','A space for patients to share their experiences at ELLE Clinic.')+testimonials()+cta();
pages.terms=()=>intro('Terms &amp; Conditions','Clear arrangements.<br>Considered care.','Preview page — final clinic terms are not yet available.')+`<section class="section legal-content"><p class="status-note">This page is a placeholder for review, not the clinic’s final Terms &amp; Conditions. This website preview cannot accept bookings, payments or account registrations.</p><h2>Appointments and fees</h2><p>Final terms will set out booking arrangements, consultation fees, treatment fees and any payment requirements.</p><h2>Cancellations and changes</h2><p>Cancellation, rescheduling, deposit and refund arrangements will be added once confirmed.</p><h2>Treatment and aftercare</h2><p>The clinic’s policies on suitability, consent, follow-up and aftercare will be included before the service opens.</p><h2>Questions or concerns</h2><p>Contact and complaints procedures will be added once the clinic details are confirmed.</p><a class="text-link" href="#contact">Contact Us ${arrow}</a></section>`;
pages.privacy=()=>intro('Privacy Policy','Your privacy matters.','Information about this local design preview.')+`<section class="section legal-content"><p class="status-note">This preview notice is not the final privacy policy for the operational clinic.</p><h2>Using this preview</h2><p>Search runs within your browser. Search queries are not sent to a service or stored by this page. Account fields are disabled. No patient details, payments or bookings are collected.</p><h2>Images and external services</h2><p>The downloadable preview contains its own images. There are no analytics, advertising scripts, tracking cookies or embedded maps. Social links have not been connected.</p><h2>Before the clinic service launches</h2><p>A full privacy policy will identify the data controller and contact details, explain how personal information is used, the applicable lawful bases, retention periods, recipients and transfers, and patients’ rights and complaint options. The selected booking and account providers will also be identified.</p><a class="text-link" href="#contact">Contact Us ${arrow}</a></section>`;
pages['create-account']=()=>account('create-account');pages.signin=()=>account('signin');
pages.information=()=>intro('Clinic information','ELLE Clinic by Dr Elmira.','London, United Kingdom')+`<section class="section legal-content"><h2>A design in progress</h2><p>The clinic address, prices, contact details and booking arrangements are still being finalised.</p><h2>Your care</h2><p>Every consultation and treatment will be personally provided by Dr Elmira. Treatment is subject to individual assessment, suitability and informed consent.</p><h2>Photography and reviews</h2><p>Model images are AI-generated illustrations. They do not show Dr Elmira, actual patients or treatment results. Testimonial spaces are explicitly marked placeholders, not patient reviews.</p></section>`;
const routeNames={home:'Home',doctor:'Meet Dr Elmira',treatments:'Treatments',fees:'Fees',contact:'Contact Us',testimonials:'Testimonials',terms:'Terms & Conditions',privacy:'Privacy Policy','create-account':'Create an Account',signin:'Sign In',information:'Clinic information',...Object.fromEntries(services.map(s=>[s.id,s.name]))};
const searchIndex=[...services.flatMap(s=>[{title:s.name,group:'Treatment category',href:'#'+s.id,keywords:s.lead},...s.items.map(item=>({title:item,group:s.name,href:treatmentHref(s,item),keywords:s.id==='other-consultations'?'symptoms assessment consultation referral':''}))]),...Object.entries(routeNames).filter(([id])=>!services.some(s=>s.id===id)).map(([id,title])=>({title,group:'Clinic information',href:'#'+id,keywords:id==='contact'?'address telephone phone email Google Maps location London opening hours Monday Tuesday Wednesday Thursday Friday Saturday Sunday':id==='doctor'?'Elmira qualifications GMC registered MD Harley Academy':id==='fees'?'prices costs pricing':id==='signin'?'login log in account':id==='testimonials'?'reviews experiences patients':''}))];
const normalise=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function findResults(query){const tokens=normalise(query).split(' ').filter(Boolean);if(!tokens.length)return [];return searchIndex.filter(item=>tokens.every(t=>normalise(item.title+' '+item.group+' '+item.keywords).includes(t))).sort((a,b)=>Number(normalise(b.title).includes(normalise(query)))-Number(normalise(a.title).includes(normalise(query))));}
const main=document.getElementById('main'),nav=document.getElementById('navigation'),toggle=document.querySelector('.menu-toggle'),booking=document.getElementById('booking'),searchDialog=document.getElementById('site-search'),searchInput=document.getElementById('search-input'),searchResults=document.getElementById('search-results'),searchCount=document.getElementById('search-count');
function updateSearch(){const query=searchInput.value.trim();if(!query){searchCount.textContent='Search all treatments and clinic information.';searchResults.innerHTML='<p class="search-hint">Examples: Profhilo, jawline, fees, opening hours.</p>';return}const results=findResults(query);searchCount.textContent=results.length?`${results.length} result${results.length===1?'':'s'} found.`:'No matches found. Try a treatment name or a shorter phrase.';searchResults.innerHTML=results.length?'<ul class="search-result-list">'+results.map(r=>`<li><a href="${r.href}" data-search-result><span>${r.title}</span><small>${r.group}</small>${arrow}</a></li>`).join('')+'</ul>':'<a class="text-link" href="#treatments" data-search-result>Browse all treatments '+arrow+'</a>';}
function render(){const parts=location.hash.slice(1).split('/');let route=parts[0]||'home';if(route==='main'){main.focus();return}const valid=Object.hasOwn(pages,route);main.innerHTML=`<div class="route">${valid?pages[route]():'<section class="not-found"><h1>Page not found</h1><a class="text-link" href="#home">Return home →</a></section>'}</div>`;const active=services.some(s=>s.id===route)?'treatments':route;document.querySelectorAll('[data-nav]').forEach(a=>{a.removeAttribute('aria-current');if(a.dataset.nav===active)a.setAttribute('aria-current','page')});nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.title=(valid?routeNames[route]:'Page not found')+' | ELLE Clinic by Dr Elmira';window.scrollTo(0,0);if(parts[1]&&services.some(s=>s.id===route)){const detail=document.getElementById(parts[1]);if(detail&&detail.tagName==='DETAILS'){detail.open=true;detail.scrollIntoView({block:'center'});const summary=detail.querySelector('summary');summary.focus({preventScroll:true});return}}main.focus({preventScroll:true});}
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});
document.addEventListener('click',e=>{const el=e.target;if(el.closest('[data-book]'))booking.showModal();if(el.closest('[data-search]')){searchDialog.showModal();updateSearch();searchInput.focus()}if(el.closest('[data-close]'))el.closest('dialog').close();const social=el.closest('[data-social]');if(social){document.getElementById('social-title').textContent=social.dataset.social;document.getElementById('social-preview').showModal()}const result=el.closest('[data-search-result]');if(result){searchDialog.close();if(result.hash===location.hash)render()}});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}}));
searchInput.addEventListener('input',updateSearch);document.getElementById('search-form').addEventListener('submit',e=>{e.preventDefault();updateSearch()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}});
window.addEventListener('hashchange',render);render();
